---
version: "2"
checks:
  method-complexity:
    enabled: false
engines:
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: C
  duplication:
    enabled: true
    config:
      languages:
      - python
ratings:
  paths:
  - "**.py"
exclude_paths:
- dist/
- tests/
- docs/
